version: '3'
services:
  estate-bot:
    build:
      context: .
    container_name: estate-bot-container
    volumes:
      - ./src/estates.json:/app/src/estates.json  # Mount JSON file from host to container
    ports:
      - "80:80"  # Expose port 80 for the app
    command: ["python", "src/bot.py"]  # Command to run the Python script
